bot:
  token: 123
  prefix: ???,

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/botbotDB
    username: postgres
    password: admin

logging:
  level:
    ru.pasvitas.discordbots.examplebot: DEBUG

